language: java
dist: trusty
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
script:
  - ./gradlew build --scan -s
  - ./gradlew build jibDockerBuild
